name: build

on:
  push:
    branches:
    - '**'
  workflow_dispatch:
    branches:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  rust-examples-ckb:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          **/Cargo.lock
          **/bindings/rust-examples/ckb/target
        key: ${{ runner.os }}-cargo-rust-examples-ckb-14
        restore-keys: ${{ runner.os }}-cargo-rust-examples-ckb-13

    - uses: cachix/install-nix-action@v20

    - name: Install ckb-debugger
      run: |
        wget 'https://github.com/nervosnetwork/ckb-standalone-debugger/releases/download/v0.107.0/ckb-debugger-linux-x64.tar.gz'
        tar zxvf ckb-debugger-linux-x64.tar.gz
        chmod +x ckb-debugger
        cp ckb-debugger ~/.cargo/bin
        ckb-debugger --version

    - name: Rust
      shell: bash
      working-directory: ./bindings/rust-examples/ckb
      run: |
        rustc --version --verbose
        rustup target add riscv64imac-unknown-none-elf
        export CC_riscv64imac_unknown_none_elf="$(nix build --print-out-paths --no-link "nixpkgs#pkgsCross.riscv64-embedded.stdenv.cc.out" 2>/dev/null)/bin/riscv64-none-elf-gcc"
        export CARGO_TARGET_RISCV64IMAC_UNKNOWN_NONE_ELF_RUNNER="env RUST_BACKTRACE=1 RUST_LOG=debug ckb-debugger --max-cycles 9999999999999 --bin"
        cargo run --target=riscv64imac-unknown-none-elf
        rm -rf target/.rustc_info.json
        rm -rf target/{debug,release}/incremental
        rm -rf ~/.cargo/registry/src
        rm -rf ~/.cargo/registry/index/*/.cache

